<HTML>
<HEAD>
<meta charset="UTF-8">
<title>wirftNichts - doc</title>
<link rel="stylesheet" href="../../style.css">
</HEAD>
<BODY>
<a href="../index.html">doc</a>&nbsp;/&nbsp;<a href="index.html">ch.tutteli.atrium.api.cc.de_CH</a>&nbsp;/&nbsp;<a href="./wirft-nichts.html">wirftNichts</a><br/>
<br/>
<h1>wirftNichts</h1>
<a name="ch.tutteli.atrium.api.cc.de_CH$wirftNichts(ch.tutteli.atrium.domain.creating.throwable.thrown.ThrowableThrown.Builder)"></a>
<code><span class="keyword">fun </span><a href="../ch.tutteli.atrium.domain.creating.throwable.thrown/-throwable-thrown/-builder/index.html"><span class="identifier">ThrowableThrown.Builder</span></a><span class="symbol">.</span><s><span class="identifier">wirftNichts</span></s><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a></code><br/>
<strong>Deprecated:</strong> api-cc-de_CH is discontinued, switch to api-fluent-en_GB; will be removed with 1.0.0<br/>
<br/>
<p>Makes the assertion that no <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html">Throwable</a> is thrown at all.</p>
<h3>Exceptions</h3>
<p><a name="AssertionError"></a>
<code>AssertionError</code> - Might throw an <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-assertion-error/index.html">AssertionError</a> if the assertion made is not correct.</p>
<p><strong>Return</strong><br/>
Notice, that this assertion function cannot provide a fluent API because we assume nothing happens,
so there is nothing we could make assertions on in addition.</p>
</BODY>
</HTML>
